project_id = "libertyconnect"

[api]
  port = 54321
  schemas = ["public", "storage", "graphql_public"]
  extra_search_path = ["public", "extensions", "vault"]

[db]
  major_version = 15

[studio]
  port = 54323

[functions]
  schemas = ["public"]

  [functions.env]
    SUPABASE_URL = { from_env = "SUPABASE_URL" }
    SUPABASE_ANON_KEY = { from_env = "SUPABASE_ANON_KEY" }
    SERVICE_ROLE_KEY = { from_env = "SUPABASE_SERVICE_ROLE_KEY" }
    EDGE_FUNCTION_BASE_URL = { from_env = "EDGE_FUNCTION_BASE_URL" }

[app.settings]
  event_reminder_cron = "* * * * *"
  housekeeping_cron = "0 * * * *"
