project_id = "libertyconnect"

[api]
  port = 54321
  schemas = ["public", "storage", "graphql_public"]
  extra_search_path = ["public", "extensions", "vault"]

[db]
  major_version = 15

[studio]
  port = 54323

# Application-specific scheduling defaults documented separately.
# event_reminder_cron = "* * * * *"
# housekeeping_cron = "0 * * * *"
